# Generated by Django 3.2.9 on 2021-12-29 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('rank', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField(default='2021-12-29')),
                ('password', models.CharField(max_length=32)),
                ('rank', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default='2021-12-29')),
                ('context', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_id', models.IntegerField()),
                ('hotel_name', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=32)),
                ('price', models.IntegerField(default=100)),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('date', models.DateField(default='2021-12-29')),
                ('rank', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='HotelDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('date', models.DateField()),
                ('price', models.IntegerField(default=100)),
                ('sales', models.IntegerField(default=233)),
                ('score', models.DecimalField(decimal_places=8, default=5.0, max_digits=16)),
                ('platform', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backdb.platform')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=128)),
                ('picture', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.CharField(default='经济型', max_length=32)),
                ('sales', models.IntegerField(default=100)),
                ('score_count', models.IntegerField(default=100)),
                ('price', models.IntegerField(default=100)),
                ('popularity', models.IntegerField(default=6666)),
                ('score', models.DecimalField(decimal_places=8, default=5.0, max_digits=16)),
                ('longlatitude', models.CharField(default='0.0, 0.0', max_length=64)),
                ('url', models.CharField(default='', max_length=256)),
                ('business', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backdb.business')),
                ('platform', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backdb.platform')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default='2021-12-29')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backdb.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backdb.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_Reply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default='2021-12-29')),
                ('context', models.CharField(max_length=500)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backdb.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backdb.user')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backdb.hotel'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backdb.user'),
        ),
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
                ('time', models.DateTimeField(default='2021-12-29')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backdb.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backdb.user')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default='2021-12-29')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backdb.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backdb.user')),
            ],
        ),
    ]
