# Generated by Django 3.2.9 on 2021-12-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default='2021-12-29'),
        ),
        migrations.AlterField(
            model_name='collections',
            name='time',
            field=models.DateField(default='2021-12-29'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default='2021-12-29'),
        ),
        migrations.AlterField(
            model_name='comment_reply',
            name='date',
            field=models.DateField(default='2021-12-29'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(default='2021-12-29'),
        ),
    ]
