# Generated by Django 3.2.9 on 2021-12-30 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backdb', '0004_auto_20211230_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backdb.business'),
        ),
    ]
