# Generated by Django 3.2.9 on 2021-12-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backdb', '0005_alter_hotel_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='hotel_id',
            field=models.IntegerField(blank=True),
        ),
    ]
