# Generated by Django 3.2.9 on 2021-12-30 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backdb', '0006_alter_room_hotel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='platform_id',
            new_name='platform',
        ),
    ]
