# Generated by Django 3.2.9 on 2021-12-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backdb', '0007_rename_platform_id_room_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='hotel_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
